name: clang CI [ubuntu,macos] 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu-clang:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make CC=clang clean all

  build-macos-clang:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make 
      run: make CC=clang clean all
